GET https://api.zoom.us/v2/users/me
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ

###

GET https://api.zoom.us/v2/users/me/meetings
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ

###
# "Registration has not been enabled for this meeting: 76873026997."
GET https://api.zoom.us/v2/meetings/76873026997/registrants
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ

###
# "Only available for Paid account: _Rwf4DgCT5mUJWB_f2FBrA."
GET https://api.zoom.us/v2/past_meetings/t9CXsXXfQdGV4435oSXCNQ==/participants
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ

###
# "Meeting does not exist: d/gV0xSeTwOR3avLCfaxRA==."
GET https://api.zoom.us/v2/past_meetings/d/gV0xSeTwOR3avLCfaxRA==
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ

###
GET https://api.zoom.us/v2/report/users/me/meetings
    ?from='2021-12-01'
    &to='2021-12-31'
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInYiOiIyLjAiLCJraWQiOiJlODI2YTQwMi0wYTAxLTQwODQtOTMyZi0yM2VjMjE3ZjI5MGIifQ.eyJ2ZXIiOjcsImF1aWQiOiJkYmNkMTlhNTJlMjk3ZjI5YmVmNDMxYTcxMWUyNTdhMyIsImNvZGUiOiJjbTNtdzVTUTVPXzBwMzJqWVhDU09DeEpzVjNscVhaZHciLCJpc3MiOiJ6bTpjaWQ6S0ZxMWlZd0hURmVKUUV4MUFhYV9kdyIsImdubyI6MCwidHlwZSI6MCwidGlkIjowLCJhdWQiOiJodHRwczovL29hdXRoLnpvb20udXMiLCJ1aWQiOiIwcDMyallYQ1NPQ3hKc1YzbHFYWmR3IiwibmJmIjoxNjQwNjAxNjgzLCJleHAiOjE2NDA2MDUyODMsImlhdCI6MTY0MDYwMTY4MywiYWlkIjoiX1J3ZjREZ0NUNW1VSldCX2YyRkJyQSIsImp0aSI6Ijg2YzUwYTliLTM0NmQtNGYxMi04OTY5LTA1OTdlNGJmMTAyNCJ9.y7TvRQOPIZHOpKmyPZgyh6zhXGZbyRV9yT6FWW3ahvVcWf2I0l_l_VqAwwYdPE2uZyt9tAmFLtn39VGHv6UQNQ